export const COUNTY_OPTIONS = [
  { key: 'Budapest', label: 'Budapest' },
  { key: 'Bacs-Kiskun', label: 'Bács-Kiskun' },
  { key: 'Baranya', label: 'Baranya' },
  { key: 'Bekes', label: 'Békés' },
  { key: 'Borsod-Abauj-Zemplen', label: 'Borsod-Abaúj-Zemplén' },
  { key: 'Csongrad-Csanad', label: 'Csongrád-Csanád' },
  { key: 'Fejer', label: 'Fejér' },
  { key: 'Gyor-Moson-Sopron', label: 'Győr-Moson-Sopron' },
  { key: 'Hajdu-Bihar', label: 'Hajdú-Bihar' },
  { key: 'Heves', label: 'Heves' },
  { key: 'Jasz-Nagykun-Szolnok', label: 'Jász-Nagykun-Szolnok' },
  { key: 'Komarom-Esztergom', label: 'Komárom-Esztergom' },
  { key: 'Nograd', label: 'Nógrád' },
  { key: 'Pest', label: 'Pest' },
  { key: 'Somogy', label: 'Somogy' },
  { key: 'Szabolcs-Szatmar-Bereg', label: 'Szabolcs-Szatmár-Bereg' },
  { key: 'Tolna', label: 'Tolna' },
  { key: 'Vas', label: 'Vas' },
  { key: 'Veszprem', label: 'Veszprém' },
  { key: 'Zala', label: 'Zala' }
];

export const CITY_COORDINATES = {
  Budapest: [47.4979, 19.0402],
  Kecskemet: [46.9062, 19.6913],
  Baja: [46.1745, 18.9543],
  Kiskunhalas: [46.434, 19.4848],
  Pecs: [46.0727, 18.2323],
  Komlo: [46.1928, 18.2649],
  Bekescsaba: [46.6736, 21.0877],
  Gyula: [46.6473, 21.2784],
  Bekes: [46.7681, 21.1319],
  Oroshaza: [46.5668, 20.6696],
  Miskolc: [48.1031, 20.7784],
  Kazincbarcika: [48.2531, 20.6454],
  Ozd: [48.2241, 20.2869],
  Szeged: [46.253, 20.1414],
  Szekesfehervar: [47.186, 18.4221],
  Dunaujvaros: [46.9619, 18.9355],
  Gyor: [47.6875, 17.6504],
  Sopron: [47.6817, 16.5845],
  Debrecen: [47.5316, 21.6273],
  Eger: [47.9025, 20.3772],
  Gyongyos: [47.7826, 19.928],
  Hatvan: [47.6667, 19.6833],
  Szolnok: [47.1754, 20.1947],
  Jaszbereny: [47.5003, 19.9111],
  Tatabanya: [47.5692, 18.4044],
  Esztergom: [47.7928, 18.7431],
  Komarom: [47.7432, 18.1191],
  Salgotarjan: [48.0935, 19.7995],
  Balassagyarmat: [48.078, 19.2967],
  Batoryterenye: [47.9686, 19.8408],
  Dunakeszi: [47.6364, 19.1386],
  Erd: [47.3918, 18.9045],
  Budaors: [47.4618, 18.9585],
  Szentendre: [47.6694, 19.0756],
  Godollo: [47.5966, 19.3552],
  Vecses: [47.4059, 19.2589],
  Dunaharaszti: [47.3533, 19.0982],
  Vac: [47.7826, 19.1332],
  Kaposvar: [46.3594, 17.7968],
  Siofok: [46.9091, 18.0519],
  Marcali: [46.585, 17.4119],
  Nyiregyhaza: [47.9558, 21.7167],
  Kisvarda: [48.2169, 22.0833],
  Szekszard: [46.3474, 18.7062],
  Paks: [46.6265, 18.8542],
  Dombovar: [46.3766, 18.136],
  Szombathely: [47.2307, 16.6218],
  Kormend: [47.0109, 16.6055],
  Sarvar: [47.253, 16.9358],
  Veszprem: [47.0931, 17.9115],
  Balatonfured: [46.9619, 17.8712],
  Tapolca: [46.8826, 17.4412],
  Zalaegerszeg: [46.8417, 16.8416],
  Heviz: [46.7903, 17.1841],
  Nagykanizsa: [46.4535, 16.991],
  Keszthely: [46.7681, 17.2511]
};

const createGym = (name, countyKey, cityKey, rank, mapQuery) => {
  const [lat, lng] = CITY_COORDINATES[cityKey];
  const countyLabel = COUNTY_OPTIONS.find((county) => county.key === countyKey)?.label || countyKey;
  const cityLabel = cityKey
    .replace('Kecskemet', 'Kecskemét')
    .replace('Pecs', 'Pécs')
    .replace('Bekescsaba', 'Békéscsaba')
    .replace('Szekesfehervar', 'Székesfehérvár')
    .replace('Gyor', 'Győr')
    .replace('Gyongyos', 'Gyöngyös')
    .replace('Jaszbereny', 'Jászberény')
    .replace('Komarom', 'Komárom')
    .replace('Batoryterenye', 'Bátonyterenye')
    .replace('Erd', 'Érd')
    .replace('Godollo', 'Gödöllő')
    .replace('Kaposvar', 'Kaposvár')
    .replace('Nyiregyhaza', 'Nyíregyháza')
    .replace('Szekszard', 'Szekszárd')
    .replace('Sarvar', 'Sárvár')
    .replace('Veszprem', 'Veszprém')
    .replace('Balatonfured', 'Balatonfüred')
    .replace('Heviz', 'Hévíz')
    .replace('Ozd', 'Ózd')
    .replace('Kormend', 'Körmend');
  return {
    name,
    countyKey,
    countyLabel,
    cityKey,
    cityLabel,
    address: `${cityLabel}, ${countyLabel}`,
    lat,
    lng,
    rank,
    mapQuery: mapQuery || `${name} ${cityLabel}`
  };
};

export const ALL_GYMS = [
  createGym('4% Fitness GYM', 'Budapest', 'Budapest', 1),
  createGym('Scitec Gold Fitness Club', 'Budapest', 'Budapest', 2),
  createGym('Chili Fitness', 'Budapest', 'Budapest', 3),
  createGym('Prestige Fitness & Wellness', 'Budapest', 'Budapest', 4),
  createGym('Flex Gym Budapest', 'Budapest', 'Budapest', 5),
  createGym('Global Fitness', 'Budapest', 'Budapest', 6),
  createGym('Power Fitness', 'Budapest', 'Budapest', 7),
  createGym('Go Active', 'Budapest', 'Budapest', 8),
  createGym('River Fitness', 'Budapest', 'Budapest', 9),
  createGym('Cutler Gym Budapest', 'Budapest', 'Budapest', 10),
  createGym('Cutler Gym Kecskemét', 'Bacs-Kiskun', 'Kecskemet', 1),
  createGym('Fitness Five Kecskemét', 'Bacs-Kiskun', 'Kecskemet', 2),
  createGym('GymTronic Kecskemét', 'Bacs-Kiskun', 'Kecskemet', 3),
  createGym('Body World Fitness', 'Bacs-Kiskun', 'Kecskemet', 4),
  createGym('Diamond Fitness', 'Bacs-Kiskun', 'Kecskemet', 5),
  createGym('Fit Club Kecskemét', 'Bacs-Kiskun', 'Kecskemet', 6),
  createGym('Sunshine Fitness', 'Bacs-Kiskun', 'Kecskemet', 7),
  createGym('Gym Factory Kecskemét', 'Bacs-Kiskun', 'Kecskemet', 8),
  createGym('Fitness Zone Baja', 'Bacs-Kiskun', 'Baja', 9),
  createGym('Iron Gym Kiskunhalas', 'Bacs-Kiskun', 'Kiskunhalas', 10),
  createGym('Cutler Gym Pécs', 'Baranya', 'Pecs', 1),
  createGym('Fitness 5 Pécs', 'Baranya', 'Pecs', 2),
  createGym('Life1 Pécs', 'Baranya', 'Pecs', 3),
  createGym('Gymtronic Pécs', 'Baranya', 'Pecs', 4),
  createGym('Mandala Fitness', 'Baranya', 'Pecs', 5),
  createGym('Fit Club Pécs', 'Baranya', 'Pecs', 6),
  createGym('Body World Pécs', 'Baranya', 'Pecs', 7),
  createGym('Atlas Fitness', 'Baranya', 'Pecs', 8),
  createGym('Hardcore Gym Pécs', 'Baranya', 'Pecs', 9),
  createGym('Fitness World Komló', 'Baranya', 'Komlo', 10),
  createGym('Cutler Gym Békéscsaba', 'Bekes', 'Bekescsaba', 1),
  createGym('Fitness Five Békéscsaba', 'Bekes', 'Bekescsaba', 2),
  createGym('Gym Center Békéscsaba', 'Bekes', 'Bekescsaba', 3),
  createGym('Fit Forma Gym', 'Bekes', 'Bekescsaba', 4),
  createGym('Body Fitness Békéscsaba', 'Bekes', 'Bekescsaba', 5),
  createGym('Iron Gym Gyula', 'Bekes', 'Gyula', 6),
  createGym('Gym Factory Gyula', 'Bekes', 'Gyula', 7),
  createGym('Energy Fitness Békés', 'Bekes', 'Bekes', 8),
  createGym('Fit Club Orosháza', 'Bekes', 'Oroshaza', 9),
  createGym('Hardcore Gym Békés', 'Bekes', 'Bekes', 10),
  createGym('BB Gym Miskolc', 'Borsod-Abauj-Zemplen', 'Miskolc', 1),
  createGym('Cutler Gym Miskolc', 'Borsod-Abauj-Zemplen', 'Miskolc', 2),
  createGym('Fitness Five Miskolc', 'Borsod-Abauj-Zemplen', 'Miskolc', 3),
  createGym('GymTronic Miskolc', 'Borsod-Abauj-Zemplen', 'Miskolc', 4),
  createGym('Hardcore Gym Miskolc', 'Borsod-Abauj-Zemplen', 'Miskolc', 5),
  createGym('Energy Fitness Kazincbarcika', 'Borsod-Abauj-Zemplen', 'Kazincbarcika', 6),
  createGym('Fit Club Ózd', 'Borsod-Abauj-Zemplen', 'Ozd', 7),
  createGym('Atlas Gym Miskolc', 'Borsod-Abauj-Zemplen', 'Miskolc', 8),
  createGym('Fitness World Miskolc', 'Borsod-Abauj-Zemplen', 'Miskolc', 9),
  createGym('Iron Gym Miskolc', 'Borsod-Abauj-Zemplen', 'Miskolc', 10),
  createGym('Cutler Gym Szeged', 'Csongrad-Csanad', 'Szeged', 1),
  createGym('Global Fitness Szeged', 'Csongrad-Csanad', 'Szeged', 2),
  createGym('Fitness Five Szeged', 'Csongrad-Csanad', 'Szeged', 3),
  createGym('GymTronic Szeged', 'Csongrad-Csanad', 'Szeged', 4),
  createGym('Hardcore Gym Szeged', 'Csongrad-Csanad', 'Szeged', 5),
  createGym('Fit World Szeged', 'Csongrad-Csanad', 'Szeged', 6),
  createGym('Body World Szeged', 'Csongrad-Csanad', 'Szeged', 7),
  createGym('Energy Fitness Szeged', 'Csongrad-Csanad', 'Szeged', 8),
  createGym('CrossFit Szeged', 'Csongrad-Csanad', 'Szeged', 9),
  createGym('Gym Factory Szeged', 'Csongrad-Csanad', 'Szeged', 10),
  createGym('Cutler Gym Székesfehérvár', 'Fejer', 'Szekesfehervar', 1),
  createGym('Fitness Five Székesfehérvár', 'Fejer', 'Szekesfehervar', 2),
  createGym('GymTronic Székesfehérvár', 'Fejer', 'Szekesfehervar', 3),
  createGym('Body World Székesfehérvár', 'Fejer', 'Szekesfehervar', 4),
  createGym('Hardcore Gym Székesfehérvár', 'Fejer', 'Szekesfehervar', 5),
  createGym('Fit Club Dunaújváros', 'Fejer', 'Dunaujvaros', 6),
  createGym('Energy Fitness Dunaújváros', 'Fejer', 'Dunaujvaros', 7),
  createGym('Atlas Gym Fehérvár', 'Fejer', 'Szekesfehervar', 8),
  createGym('Iron Gym Dunaújváros', 'Fejer', 'Dunaujvaros', 9),
  createGym('Fitness World Fehérvár', 'Fejer', 'Szekesfehervar', 10),
  createGym('Cutler Gym Győr', 'Gyor-Moson-Sopron', 'Gyor', 1),
  createGym('GymTronic Győr', 'Gyor-Moson-Sopron', 'Gyor', 2),
  createGym('Miami Gym Győr', 'Gyor-Moson-Sopron', 'Gyor', 3),
  createGym('Fox Gym Győr', 'Gyor-Moson-Sopron', 'Gyor', 4),
  createGym('Fitness Five Győr', 'Gyor-Moson-Sopron', 'Gyor', 5),
  createGym('Iron Gym Győr', 'Gyor-Moson-Sopron', 'Gyor', 6),
  createGym('Atlas Gym Győr', 'Gyor-Moson-Sopron', 'Gyor', 7),
  createGym('Fit Club Sopron', 'Gyor-Moson-Sopron', 'Sopron', 8),
  createGym('Energy Fitness Sopron', 'Gyor-Moson-Sopron', 'Sopron', 9),
  createGym('Hardcore Gym Győr', 'Gyor-Moson-Sopron', 'Gyor', 10),
  createGym('Fitness Five Debrecen', 'Hajdu-Bihar', 'Debrecen', 1),
  createGym('Cutler Gym Debrecen', 'Hajdu-Bihar', 'Debrecen', 2),
  createGym('GymTronic Debrecen', 'Hajdu-Bihar', 'Debrecen', 3),
  createGym('Body World Debrecen', 'Hajdu-Bihar', 'Debrecen', 4),
  createGym('Iron Gym Debrecen', 'Hajdu-Bihar', 'Debrecen', 5),
  createGym('Energy Fitness Debrecen', 'Hajdu-Bihar', 'Debrecen', 6),
  createGym('Atlas Gym Debrecen', 'Hajdu-Bihar', 'Debrecen', 7),
  createGym('Hardcore Gym Debrecen', 'Hajdu-Bihar', 'Debrecen', 8),
  createGym('Fit Club Debrecen', 'Hajdu-Bihar', 'Debrecen', 9),
  createGym('CrossFit Debrecen', 'Hajdu-Bihar', 'Debrecen', 10),
  createGym('Fitness Five Eger', 'Heves', 'Eger', 1),
  createGym('Cutler Gym Eger', 'Heves', 'Eger', 2),
  createGym('GymTronic Eger', 'Heves', 'Eger', 3),
  createGym('Body World Eger', 'Heves', 'Eger', 4),
  createGym('Iron Gym Eger', 'Heves', 'Eger', 5),
  createGym('Atlas Gym Eger', 'Heves', 'Eger', 6),
  createGym('Hardcore Gym Eger', 'Heves', 'Eger', 7),
  createGym('Energy Fitness Gyöngyös', 'Heves', 'Gyongyos', 8),
  createGym('Fit Club Hatvan', 'Heves', 'Hatvan', 9),
  createGym('Fitness World Eger', 'Heves', 'Eger', 10),
  createGym('Cutler Gym Szolnok', 'Jasz-Nagykun-Szolnok', 'Szolnok', 1),
  createGym('Fitness Five Szolnok', 'Jasz-Nagykun-Szolnok', 'Szolnok', 2),
  createGym('GymTronic Szolnok', 'Jasz-Nagykun-Szolnok', 'Szolnok', 3),
  createGym('Body World Szolnok', 'Jasz-Nagykun-Szolnok', 'Szolnok', 4),
  createGym('Iron Gym Szolnok', 'Jasz-Nagykun-Szolnok', 'Szolnok', 5),
  createGym('Energy Fitness Szolnok', 'Jasz-Nagykun-Szolnok', 'Szolnok', 6),
  createGym('Atlas Gym Szolnok', 'Jasz-Nagykun-Szolnok', 'Szolnok', 7),
  createGym('Hardcore Gym Szolnok', 'Jasz-Nagykun-Szolnok', 'Szolnok', 8),
  createGym('Fit Club Jászberény', 'Jasz-Nagykun-Szolnok', 'Jaszbereny', 9),
  createGym('Fitness World Szolnok', 'Jasz-Nagykun-Szolnok', 'Szolnok', 10),
  createGym('Cutler Gym Tatabánya', 'Komarom-Esztergom', 'Tatabanya', 1),
  createGym('Fitness Five Tatabánya', 'Komarom-Esztergom', 'Tatabanya', 2),
  createGym('GymTronic Tatabánya', 'Komarom-Esztergom', 'Tatabanya', 3),
  createGym('Body World Tatabánya', 'Komarom-Esztergom', 'Tatabanya', 4),
  createGym('Iron Gym Tatabánya', 'Komarom-Esztergom', 'Tatabanya', 5),
  createGym('Atlas Gym Tatabánya', 'Komarom-Esztergom', 'Tatabanya', 6),
  createGym('Hardcore Gym Tatabánya', 'Komarom-Esztergom', 'Tatabanya', 7),
  createGym('Energy Fitness Esztergom', 'Komarom-Esztergom', 'Esztergom', 8),
  createGym('Fit Club Komárom', 'Komarom-Esztergom', 'Komarom', 9),
  createGym('Fitness World Tatabánya', 'Komarom-Esztergom', 'Tatabanya', 10),
  createGym('Fitness Five Salgótarján', 'Nograd', 'Salgotarjan', 1),
  createGym('Cutler Gym Salgótarján', 'Nograd', 'Salgotarjan', 2),
  createGym('GymTronic Salgótarján', 'Nograd', 'Salgotarjan', 3),
  createGym('Body World Salgótarján', 'Nograd', 'Salgotarjan', 4),
  createGym('Iron Gym Salgótarján', 'Nograd', 'Salgotarjan', 5),
  createGym('Atlas Gym Salgótarján', 'Nograd', 'Salgotarjan', 6),
  createGym('Hardcore Gym Salgótarján', 'Nograd', 'Salgotarjan', 7),
  createGym('Energy Fitness Balassagyarmat', 'Nograd', 'Balassagyarmat', 8),
  createGym('Fit Club Bátonyterenye', 'Nograd', 'Batoryterenye', 9),
  createGym('Fitness World Salgótarján', 'Nograd', 'Salgotarjan', 10),
  createGym('Cutler Gym Dunakeszi', 'Pest', 'Dunakeszi', 1),
  createGym('Fitness Five Érd', 'Pest', 'Erd', 2),
  createGym('GymTronic Budaörs', 'Pest', 'Budaors', 3),
  createGym('Body World Szentendre', 'Pest', 'Szentendre', 4),
  createGym('Iron Gym Gödöllő', 'Pest', 'Godollo', 5),
  createGym('Atlas Gym Érd', 'Pest', 'Erd', 6),
  createGym('Hardcore Gym Vecsés', 'Pest', 'Vecses', 7),
  createGym('Energy Fitness Dunaharaszti', 'Pest', 'Dunaharaszti', 8),
  createGym('Fit Club Vác', 'Pest', 'Vac', 9),
  createGym('Fitness World Érd', 'Pest', 'Erd', 10),
  createGym('Cutler Gym Kaposvár', 'Somogy', 'Kaposvar', 1),
  createGym('Fitness Five Kaposvár', 'Somogy', 'Kaposvar', 2),
  createGym('GymTronic Kaposvár', 'Somogy', 'Kaposvar', 3),
  createGym('Body World Kaposvár', 'Somogy', 'Kaposvar', 4),
  createGym('Iron Gym Kaposvár', 'Somogy', 'Kaposvar', 5),
  createGym('Atlas Gym Kaposvár', 'Somogy', 'Kaposvar', 6),
  createGym('Hardcore Gym Kaposvár', 'Somogy', 'Kaposvar', 7),
  createGym('Energy Fitness Siófok', 'Somogy', 'Siofok', 8),
  createGym('Fit Club Marcali', 'Somogy', 'Marcali', 9),
  createGym('Fitness World Kaposvár', 'Somogy', 'Kaposvar', 10),
  createGym('Fitness Five Nyíregyháza', 'Szabolcs-Szatmar-Bereg', 'Nyiregyhaza', 1),
  createGym('Cutler Gym Nyíregyháza', 'Szabolcs-Szatmar-Bereg', 'Nyiregyhaza', 2),
  createGym('GymTronic Nyíregyháza', 'Szabolcs-Szatmar-Bereg', 'Nyiregyhaza', 3),
  createGym('Body World Nyíregyháza', 'Szabolcs-Szatmar-Bereg', 'Nyiregyhaza', 4),
  createGym('Iron Gym Nyíregyháza', 'Szabolcs-Szatmar-Bereg', 'Nyiregyhaza', 5),
  createGym('Atlas Gym Nyíregyháza', 'Szabolcs-Szatmar-Bereg', 'Nyiregyhaza', 6),
  createGym('Hardcore Gym Nyíregyháza', 'Szabolcs-Szatmar-Bereg', 'Nyiregyhaza', 7),
  createGym('Energy Fitness Nyíregyháza', 'Szabolcs-Szatmar-Bereg', 'Nyiregyhaza', 8),
  createGym('Fit Club Kisvárda', 'Szabolcs-Szatmar-Bereg', 'Kisvarda', 9),
  createGym('Fitness World Nyíregyháza', 'Szabolcs-Szatmar-Bereg', 'Nyiregyhaza', 10),
  createGym('Fitness Five Szekszárd', 'Tolna', 'Szekszard', 1),
  createGym('Cutler Gym Szekszárd', 'Tolna', 'Szekszard', 2),
  createGym('GymTronic Szekszárd', 'Tolna', 'Szekszard', 3),
  createGym('Body World Szekszárd', 'Tolna', 'Szekszard', 4),
  createGym('Iron Gym Szekszárd', 'Tolna', 'Szekszard', 5),
  createGym('Atlas Gym Szekszárd', 'Tolna', 'Szekszard', 6),
  createGym('Hardcore Gym Szekszárd', 'Tolna', 'Szekszard', 7),
  createGym('Energy Fitness Paks', 'Tolna', 'Paks', 8),
  createGym('Fit Club Dombóvár', 'Tolna', 'Dombovar', 9),
  createGym('Fitness World Szekszárd', 'Tolna', 'Szekszard', 10),
  createGym('Fitness Five Szombathely', 'Vas', 'Szombathely', 1),
  createGym('Cutler Gym Szombathely', 'Vas', 'Szombathely', 2),
  createGym('GymTronic Szombathely', 'Vas', 'Szombathely', 3),
  createGym('Body World Szombathely', 'Vas', 'Szombathely', 4),
  createGym('Iron Gym Szombathely', 'Vas', 'Szombathely', 5),
  createGym('Atlas Gym Szombathely', 'Vas', 'Szombathely', 6),
  createGym('Hardcore Gym Szombathely', 'Vas', 'Szombathely', 7),
  createGym('Energy Fitness Körmend', 'Vas', 'Kormend', 8),
  createGym('Fit Club Sárvár', 'Vas', 'Sarvar', 9),
  createGym('Fitness World Szombathely', 'Vas', 'Szombathely', 10),
  createGym('Cutler Gym Veszprém', 'Veszprem', 'Veszprem', 1),
  createGym('Top Gym Fitness Club', 'Veszprem', 'Veszprem', 2),
  createGym('FüredGym', 'Veszprem', 'Balatonfured', 3),
  createGym('Colonia Fitness', 'Veszprem', 'Veszprem', 4),
  createGym('Fit’n Go Fitness', 'Veszprem', 'Veszprem', 5),
  createGym('Kettlebell Veszprém', 'Veszprem', 'Veszprem', 6),
  createGym('Optimal Fitness', 'Veszprem', 'Veszprem', 7),
  createGym('Bloom Body Fitness', 'Veszprem', 'Veszprem', 8),
  createGym('Tapolca Sportház', 'Veszprem', 'Tapolca', 9),
  createGym('Balatonfüred Fitness Club', 'Veszprem', 'Balatonfured', 10),
  createGym('Cutler Fitness Zalaegerszeg', 'Zala', 'Zalaegerszeg', 1),
  createGym('XXL Fitness Zalaegerszeg', 'Zala', 'Zalaegerszeg', 2),
  createGym('Metroflex Gym', 'Zala', 'Zalaegerszeg', 3),
  createGym('Sportutca Fitness', 'Zala', 'Zalaegerszeg', 4),
  createGym('Főnix Club & Wellness', 'Zala', 'Zalaegerszeg', 5),
  createGym('Fitness Club Hévíz', 'Zala', 'Heviz', 6),
  createGym('XBody Nagykanizsa', 'Zala', 'Nagykanizsa', 7),
  createGym('RomidA Fitness', 'Zala', 'Zalaegerszeg', 8),
  createGym('Balance Fitness Zalaegerszeg', 'Zala', 'Zalaegerszeg', 9),
  createGym('Matrix Gym Keszthely', 'Zala', 'Keszthely', 10)
];